### ISSUE TITLE
Try using the partial _variables.scss

### ISSUE THREAD

**Issue by resonantdoghouse** [lstasiuk/Instanews#7]
At the moment the variables partial is empty however you have 2 variables in your mixins partial.

Try moving the variables from your mixins to the variables partial and take it a step further by converting any colors in your css to use variables instead. It might not seem necessary for such a small site but it's a common practice and will be very helpful to know how to do this when we get to larger projects.

**Comment by lstasiuk** [comment]
moved variables partials and changed color in variable.
